### PR TITLE
Upgrade to latest remark (with support for ESM)

### PR DESCRIPTION
**Pull request by j-f1**
Closes #86.

Node.js 12.17 and above support ESM natively. Since this module needs to still be able to be consumed as CommonJS, I’ve taken advantage of the fact that Eleventy renderers are async to enable the use of dynamic `import` for Remark and Remark plugins.

Although I haven’t thoroughly tested this change, the integration test still works. Using custom plugins should continue to work — if they are ESM, they can be imported either by manually using `import()` or by passing the module name (in which case, the default export will be used).

Rollup has been removed since it tried to transform `import()` to `require()`. I don’t think there’s really a reason to bundle this, since it isn’t intended for browser use, and because the ESM version was not previously hooked up.

The test suite does not currently work, because Jest doesn’t properly support ESM.

### CODE REVIEW

**Review by florianeckerstorfer — APPROVED** [review]

**Comment by florianeckerstorfer** [comment]
@j-f1 Thanks for the PR. The last time I checked Eleventy had still problems with code that uses imports instead of require.

Do you by any chance know why the Github workflows are not running? Since you're a first-time contributor I think I need to approve this, but I don't see the _Approve and run_ button the [docs mention on this](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks).

**Comment by j-f1** [comment]
I just gave it a quick test with my local site (Eleventy `1.0.0-beta.8`) and it seems to work fine! I’d imagine it wouldn’t work well if I used static imports, but since dynamic `import()` is allowed within CommonJS modules, there shouldn’t be any issues as long as it’s ok for the code to be async.

Let me try pushing an empty commit to trigger the checks.

**Comment by j-f1** [comment]
I figured it out! The workflows were set to run on `push`, but PRs from external repos only trigger a `pull_request` event.

**Review by florianeckerstorfer — APPROVED** [review]

**Comment by florianeckerstorfer** [comment]
@j-f1 Nice, thanks a lot. I think I now need to update my workflows in a couple of repos 🤔  Anyway, thanks for figuring this out.

**Comment by j-f1** [comment]
a quick update: when using `DEBUG='Eleventy:Benchmark*'`, `time-require` is imported by 11ty. This module (which was last updated in 2014) does not work with ES Modules. See https://github.com/11ty/eleventy/issues/2129.

**Comment by j-f1** [comment]
Another update: the latest canary version of Eleventy removed `time-require`, so the ESM crash has been resolved.

**Pull request merged**
